/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screenold2;

/**
 *
 * @author Guilherme Ortiz
 */
public class ClientScreen extends javax.swing.JFrame {

    /**
     * Creates new form ClientScreen
     */
    public ClientScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pClient = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pContent = new javax.swing.JPanel();
        pcLeft = new javax.swing.JPanel();
        pcRight = new javax.swing.JPanel();
        pcCenter = new javax.swing.JPanel();
        pFooter = new javax.swing.JPanel();
        spLog1 = new javax.swing.JScrollPane();
        pLog1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pClient.setBackground(new java.awt.Color(255, 255, 255));
        pClient.setMinimumSize(new java.awt.Dimension(900, 700));
        pClient.setPreferredSize(new java.awt.Dimension(900, 700));
        pClient.setLayout(new java.awt.BorderLayout());

        pHeader.setBackground(new java.awt.Color(204, 0, 204));
        pHeader.setMinimumSize(new java.awt.Dimension(900, 70));
        pHeader.setPreferredSize(new java.awt.Dimension(900, 70));

        jButton3.setText("jButton3");

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addContainerGap(837, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton3)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pClient.add(pHeader, java.awt.BorderLayout.PAGE_START);

        pContent.setBackground(new java.awt.Color(255, 255, 255));
        pContent.setMinimumSize(new java.awt.Dimension(897, 700));
        pContent.setPreferredSize(new java.awt.Dimension(897, 700));
        pContent.setLayout(new java.awt.BorderLayout());

        pcLeft.setBackground(new java.awt.Color(255, 255, 255));
        pcLeft.setMinimumSize(new java.awt.Dimension(299, 400));
        pcLeft.setPreferredSize(new java.awt.Dimension(299, 400));

        javax.swing.GroupLayout pcLeftLayout = new javax.swing.GroupLayout(pcLeft);
        pcLeft.setLayout(pcLeftLayout);
        pcLeftLayout.setHorizontalGroup(
            pcLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        pcLeftLayout.setVerticalGroup(
            pcLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pContent.add(pcLeft, java.awt.BorderLayout.LINE_START);

        pcRight.setBackground(new java.awt.Color(255, 255, 255));
        pcRight.setMinimumSize(new java.awt.Dimension(299, 400));
        pcRight.setPreferredSize(new java.awt.Dimension(299, 330));

        javax.swing.GroupLayout pcRightLayout = new javax.swing.GroupLayout(pcRight);
        pcRight.setLayout(pcRightLayout);
        pcRightLayout.setHorizontalGroup(
            pcRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        pcRightLayout.setVerticalGroup(
            pcRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pContent.add(pcRight, java.awt.BorderLayout.LINE_END);

        pcCenter.setBackground(new java.awt.Color(255, 255, 255));
        pcCenter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pcCenter.setMinimumSize(new java.awt.Dimension(299, 400));
        pcCenter.setPreferredSize(new java.awt.Dimension(299, 330));

        javax.swing.GroupLayout pcCenterLayout = new javax.swing.GroupLayout(pcCenter);
        pcCenter.setLayout(pcCenterLayout);
        pcCenterLayout.setHorizontalGroup(
            pcCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        pcCenterLayout.setVerticalGroup(
            pcCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pContent.add(pcCenter, java.awt.BorderLayout.CENTER);

        pClient.add(pContent, java.awt.BorderLayout.CENTER);

        pFooter.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        spLog1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        spLog1.setMinimumSize(null);
        spLog1.setName(""); // NOI18N
        spLog1.setRequestFocusEnabled(false);

        pLog1.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pLog1Layout = new javax.swing.GroupLayout(pLog1);
        pLog1.setLayout(pLog1Layout);
        pLog1Layout.setHorizontalGroup(
            pLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        pLog1Layout.setVerticalGroup(
            pLog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        spLog1.setViewportView(pLog1);

        javax.swing.GroupLayout pFooterLayout = new javax.swing.GroupLayout(pFooter);
        pFooter.setLayout(pFooterLayout);
        pFooterLayout.setHorizontalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFooterLayout.createSequentialGroup()
                .addComponent(spLog1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        pFooterLayout.setVerticalGroup(
            pFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spLog1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pClient.add(pFooter, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println("teste");
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    public javax.swing.JPanel pClient;
    public javax.swing.JPanel pContent;
    public javax.swing.JPanel pFooter;
    public javax.swing.JPanel pHeader;
    public javax.swing.JPanel pLog1;
    public javax.swing.JPanel pcCenter;
    public javax.swing.JPanel pcLeft;
    public javax.swing.JPanel pcRight;
    public javax.swing.JScrollPane spLog1;
    // End of variables declaration//GEN-END:variables
}
