/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screenold;

/**
 *
 * @author Guilherme Ortiz
 */
public class Client extends javax.swing.JPanel {

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pClient = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        spLog = new javax.swing.JScrollPane();
        pLog = new javax.swing.JPanel();
        pContent = new javax.swing.JPanel();

        pClient.setPreferredSize(new java.awt.Dimension(890, 800));
        pClient.setLayout(new java.awt.BorderLayout());

        pHeader.setBackground(new java.awt.Color(204, 0, 204));
        pHeader.setMinimumSize(new java.awt.Dimension(100, 60));
        pHeader.setPreferredSize(new java.awt.Dimension(885, 60));
        pHeader.setLayout(new java.awt.BorderLayout());

        lTitle.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lTitle.setForeground(new java.awt.Color(255, 255, 255));
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("Client");
        pHeader.add(lTitle, java.awt.BorderLayout.CENTER);

        pClient.add(pHeader, java.awt.BorderLayout.PAGE_START);

        spLog.setMinimumSize(new java.awt.Dimension(100, 300));
        spLog.setPreferredSize(new java.awt.Dimension(100, 300));

        pLog.setBackground(new java.awt.Color(204, 0, 204));

        javax.swing.GroupLayout pLogLayout = new javax.swing.GroupLayout(pLog);
        pLog.setLayout(pLogLayout);
        pLogLayout.setHorizontalGroup(
            pLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        pLogLayout.setVerticalGroup(
            pLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        spLog.setViewportView(pLog);

        pClient.add(spLog, java.awt.BorderLayout.PAGE_END);

        pContent.setLayout(new java.awt.BorderLayout());
        pClient.add(pContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pClient.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lTitle;
    public javax.swing.JPanel pClient;
    public javax.swing.JPanel pContent;
    public javax.swing.JPanel pHeader;
    private javax.swing.JPanel pLog;
    public javax.swing.JScrollPane spLog;
    // End of variables declaration//GEN-END:variables
}
