/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import java.awt.Color;
import java.awt.Font;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Guilherme Ortiz
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pServer = new JPanel();
        pHeader = new JPanel();
        lTitle = new JLabel();
        pContent = new JPanel();
        spLog = new JScrollPane();
        pLog = new JPanel();
        bExit = new JButton();
        
        bExit.setBackground(Color.WHITE);
        bExit.setText("Sair");

        pServer.setBackground(new Color(255, 255, 255));

        pHeader.setBackground(new Color(204, 0, 204));

        lTitle.setFont(new Font("MV Boli", 1, 24)); // NOI18N
        lTitle.setForeground(new Color(255, 255, 255));
        lTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lTitle.setText("Client");

        GroupLayout pHeaderLayout = new GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lTitle, GroupLayout.Alignment.CENTER, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bExit, GroupLayout.Alignment.TRAILING, 100, 100, Short.MAX_VALUE)
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(lTitle, GroupLayout.Alignment.CENTER, GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(bExit, GroupLayout.Alignment.TRAILING, 100, 62, Short.MAX_VALUE)
        );

        pContent.setBackground(new Color(255, 255, 255));

        pContent.setSize(250, GroupLayout.DEFAULT_SIZE);

        spLog.setBackground(new Color(204, 0, 204));

        pLog.setBackground(new Color(204, 0, 204));

        GroupLayout pLogLayout = new GroupLayout(pLog);
        pLog.setLayout(pLogLayout);
        pLogLayout.setHorizontalGroup(
            pLogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        pLogLayout.setVerticalGroup(
            pLogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        spLog.setViewportView(pLog);

        GroupLayout pServerLayout = new GroupLayout(pServer);
        pServer.setLayout(pServerLayout);
        pServerLayout.setHorizontalGroup(
            pServerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pHeader, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, pServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pContent, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spLog, GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        pServerLayout.setVerticalGroup(
            pServerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pServerLayout.createSequentialGroup()
                .addComponent(pHeader, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pServerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(pContent, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spLog, GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pServer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(pServer, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
       
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("Client");
        pack();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lTitle;
    private JPanel pContent;
    private JPanel pLog;
    private JPanel pServer;
    private JPanel pHeader;
    private JScrollPane spLog;
    private JButton bExit;
    // End of variables declaration//GEN-END:variables
}
