/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

/**
 *
 * @author gui_o
 */
public class ServerConnection extends javax.swing.JPanel {

    /**
     * Creates new form ServerConection
     */
    public ServerConnection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pConection = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        tfIP = new javax.swing.JTextField();
        lIP = new javax.swing.JLabel();
        lPort = new javax.swing.JLabel();
        tfPort = new javax.swing.JTextField();
        bConection = new javax.swing.JButton();

        pConection.setBackground(new java.awt.Color(255, 255, 255));

        lTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lTitle.setForeground(new java.awt.Color(204, 204, 204));
        lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitle.setText("Iniciar Servidor");

        tfIP.setEditable(false);
        tfIP.setBackground(new java.awt.Color(204, 204, 204));
        tfIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfIP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIP.setText("localhost");

        lIP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lIP.setText("IP");

        lPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPort.setText("Porta");

        tfPort.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfPort.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPort.setToolTipText("");
        tfPort.setPreferredSize(new java.awt.Dimension(60, 23));

        bConection.setBackground(new java.awt.Color(204, 0, 204));
        bConection.setText("Iniciar");
        bConection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pConectionLayout = new javax.swing.GroupLayout(pConection);
        pConection.setLayout(pConectionLayout);
        pConectionLayout.setHorizontalGroup(
            pConectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pConectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(tfIP)
                    .addGroup(pConectionLayout.createSequentialGroup()
                        .addGroup(pConectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lIP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lPort))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bConection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pConectionLayout.setVerticalGroup(
            pConectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lIP)
                .addGap(3, 3, 3)
                .addComponent(tfIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bConection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pConection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bConectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bConectionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConection;
    private javax.swing.JLabel lIP;
    private javax.swing.JLabel lPort;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pConection;
    private javax.swing.JTextField tfIP;
    private javax.swing.JTextField tfPort;
    // End of variables declaration//GEN-END:variables
}
